name: Deploy to Cloud Run (PROD)

on:
  push:
    branches: [prod]  # Se ejecuta cuando hacés push a la rama 'prod'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Cloud Run (PROD)
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/chatbot-comercial ./backend
        gcloud run deploy chatbot-comercial \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/chatbot-comercial \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
