name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate with service account
      run: |
        cat <<EOF > key.json
        ${{ secrets.GCP_SA_KEY }}
        EOF
        gcloud auth activate-service-account --key-file=key.json
        gcloud config set account $(gcloud auth list --filter="status:ACTIVE" --format="value(account)")

    - name: Deploy to Cloud Run (Staging)
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/chatbot-comercial-staging ./backend
        gcloud run deploy chatbot-comercial-staging \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/chatbot-comercial-staging \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
